# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\x1a\x1bgoogle/protobuf/empty.proto\":\n\tInventory\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x0f\n\x07product\x18\x03 \x01(\t\"\x16\n\x14InventoryListRequest\"&\n\x18InventoryRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xcc\x02\n\x13InventoryController\x12\x41\n\x04List\x12\x1f.inventory.InventoryListRequest\x1a\x14.inventory.Inventory\"\x00\x30\x01\x12\x36\n\x06\x43reate\x12\x14.inventory.Inventory\x1a\x14.inventory.Inventory\"\x00\x12G\n\x08Retrieve\x12#.inventory.InventoryRetrieveRequest\x1a\x14.inventory.Inventory\"\x00\x12\x36\n\x06Update\x12\x14.inventory.Inventory\x1a\x14.inventory.Inventory\"\x00\x12\x39\n\x07\x44\x65stroy\x12\x14.inventory.Inventory\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INVENTORY']._serialized_start=59
  _globals['_INVENTORY']._serialized_end=117
  _globals['_INVENTORYLISTREQUEST']._serialized_start=119
  _globals['_INVENTORYLISTREQUEST']._serialized_end=141
  _globals['_INVENTORYRETRIEVEREQUEST']._serialized_start=143
  _globals['_INVENTORYRETRIEVEREQUEST']._serialized_end=181
  _globals['_INVENTORYCONTROLLER']._serialized_start=184
  _globals['_INVENTORYCONTROLLER']._serialized_end=516
# @@protoc_insertion_point(module_scope)
