# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecommerce__product.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x65\x63ommerce__product.proto\x12\x12\x65\x63ommerce__product\x1a\x1bgoogle/protobuf/empty.proto\"5\n\x07Product\x12\r\n\x05\x66olio\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\t\"\x14\n\x12ProductListRequest\"\'\n\x16ProductRetrieveRequest\x12\r\n\x05\x66olio\x18\x01 \x01(\t2\x89\x03\n\x11ProductController\x12O\n\x04List\x12&.ecommerce__product.ProductListRequest\x1a\x1b.ecommerce__product.Product\"\x00\x30\x01\x12\x44\n\x06\x43reate\x12\x1b.ecommerce__product.Product\x1a\x1b.ecommerce__product.Product\"\x00\x12U\n\x08Retrieve\x12*.ecommerce__product.ProductRetrieveRequest\x1a\x1b.ecommerce__product.Product\"\x00\x12\x44\n\x06Update\x12\x1b.ecommerce__product.Product\x1a\x1b.ecommerce__product.Product\"\x00\x12@\n\x07\x44\x65stroy\x12\x1b.ecommerce__product.Product\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ecommerce__product_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRODUCT']._serialized_start=77
  _globals['_PRODUCT']._serialized_end=130
  _globals['_PRODUCTLISTREQUEST']._serialized_start=132
  _globals['_PRODUCTLISTREQUEST']._serialized_end=152
  _globals['_PRODUCTRETRIEVEREQUEST']._serialized_start=154
  _globals['_PRODUCTRETRIEVEREQUEST']._serialized_end=193
  _globals['_PRODUCTCONTROLLER']._serialized_start=196
  _globals['_PRODUCTCONTROLLER']._serialized_end=589
# @@protoc_insertion_point(module_scope)
